---

- hosts: all
  become: true
  tasks:

  - name: update repository indext
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package (CentOS)
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php package (CentOS)
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS" 
