- name: install apache and php packages
  tags: apache,httpd,php
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change email address for web admin
  tags: apache,apache2,ubuntu
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: "{{'\t'}}ServerAdmin"
    line: "{{'\t'}}ServerAdmin admin@domain"
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: copy default html file to site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
