- name: add ssh key for alice
  authorized_key:
    user: alice
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHfNuN8ZeJNMdr1hN3czfu36GhZwq/G2X7qMdp6Bs8cB ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
